version: "3"
services:
  app:
    build: .
    ports:
    - 3000:3000
    volumes:
    - ./src:/usr/app/src
    networks:
    - graphql-poc
    command: npm run dev
  mongo:
    image: mongo
    ports:
    - 27017:27017
    networks:
    - graphql-poc

networks:
  graphql-poc: